name: gh-pages
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
permissions:
  contents: write
jobs:
  build:
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2

      - name: Setup .NET Core 🔧
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 7.x

      - name: Install .NET WASM Build Tools
        run: dotnet workload install wasm-tools

      - name: Publish
        run: dotnet publish ./samples/BlazorWasm/BlazorWasm.csproj -c:Release -p:GHPages=true -o dist --nologo
          
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: dist/wwwroot
